
FROM python:3.11
WORKDIR /api
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY requirements.txt /api
RUN pip3 install --upgrade pip -r requirements.txt --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org

COPY . /api
#Устанавливаем порт, который будет использоваться для сервера
EXPOSE 8080
ENTRYPOINT ["uvicorn"]
# ENTRYPOINT ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8080"]
